let books = [
  {
    title: 'Dracula - Die Wiederkehr',
    author: 'Dacre Stoker, Ian Holt',
    year: 2009,
    genre: 'Fantasy',
    price: 5.99,
    image: './assets/img/dracula.jpeg',
    likes: 5,
    liked: false,
    comments: [
      {
        userName: 'Franzy',
        userText: 'Super Buch',
      },
    ],
  },
  {
    title: 'Das Lied von Eis und Feuer Der Winter naht',
    author: 'G.R.R Martin',
    year: 1996,
    genre: 'Fantasy',
    price: 18.0,
    image: './assets/img/GOT.jpeg',
    likes: 5,
    liked: false,
    comments: [],
  },

  {
    title: 'Midgard',
    author: 'Wolfgang & Heike Hohlbein',
    year: 1987,
    genre: 'Fantasy',
    price: 15.0,
    image: './assets/img/midgard.jpeg',
    likes: 5,
    liked: false,
    comments: [],
  },
  {
    title: 'Das Silmarillion',
    author: 'Christopher Tolkien',
    year: 1977,
    genre: 'Fantasy',
    price: 28.0,
    image: './assets/img/silmarillion.jpeg',
    likes: 9,
    liked: false,
    comments: [],
  },
];
